MusicalInstrument musicalInstrument = new("musicalInstrument");
Violin violin = new("violin");
Trombone trombone = new("trombone");
Ukulele ukulele = new("ukulele");
Cello cello = new("cello");

musicalInstrument.Sound();
violin.Sound();
trombone.Sound();
ukulele.Sound();
cello.Sound();
Console.WriteLine("\n\n");
musicalInstrument.Show();
violin.Show();
trombone.Show();
ukulele.Show();
cello.Show();
Console.WriteLine("\n\n");
musicalInstrument.Desc();
violin.Desc();
trombone.Desc();
ukulele.Desc();
cello.Desc();
Console.WriteLine("\n\n");
musicalInstrument.History();
violin.History();
trombone.History();
ukulele.History();
cello.History();